services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rietberg_server
    ports:
      - "5015:5015"
    env_file:
      - .env
    environment:
      - PORT=5008
    restart: always